name: croni_mini
description: CroniMini
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  chewie: ^1.2.2
  carousel_slider: ^4.0.0

  flutter_custom_clippers: ^2.0.0

  get: ^4.6.1

  video_player: ^2.2.10

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - images/
